INSERT INTO subject(id, name, class_type_id, school_id) values (2,  'English Language',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (3,  'Mathematics',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (5,  'French',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (9,  'Agricultural Science',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (10,  'Business Studies',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (11,  'Home Economics',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (12,  'Computer Education',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (47,  'CRS/IRK',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (14,  'Physical and Health Education',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (15,  'English Language',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (16,  'Mathematics',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (17,  'Biology',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (18,  'Chemistry',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (19,  'Physics',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (20,  'Health Science',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (21,  'Literature in English',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (22,  'History',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (23,  'Geography',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (24,  'Religious Studies',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (25,  'Hausa or a major Nigerian Language',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (26,  'Agricultural Science',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (27,  'Book-keeping and Accounting',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (28,  'Commerce',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (29,  'Computer Education',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (30,  'Home Management',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (31,  'Food and Nutrition',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (32,  'Further Mathematics',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (33,  'French',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (34,  'Christian Religious Knowledge/Islamic Religious Knowledge',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (35,  'Government',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (36,  'Information Tech',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (37,  'Hausa/Igbo/ Yoruba',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (38,  'Social Studies',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (39,  'Basic Science',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (40,  'Basic Technology',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (41,  'Hausa/Igbo/ Yoruba',  '2', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (50,  'Civic Education',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (49,  'Creative Art',  '1', 1);
INSERT INTO subject(id, name, class_type_id, school_id) values (51,  'Arabic Language',  '1', 1);
