<?php
session_start();
?>
<html>
<body>

<p><a href='student.php'>AcadPro</a></p>

<a href='#1'>How to setup AcadPro?</a><br><br>
<a href='#2'>How to enter student scores?</a><br>
<a href='#3'>How to enter student non academic scores?</a><br>
<a href='#4'>How to generate and print report card for a particular student?</a><br>
<a href='#5'>How to generate and print result for all students in a class?</a><br>
<a href='#6'>How to promote/transfer a student from one class to another?</a><br><br>

<a href='#7'>How to enter student's school fees?</a><br>
<a href='#8'>How to generate and print school fees receipt for a particular student?</a><br>
<a href='#9'>How to generate and print class receipt for all students in a class?</a><br><br>

<a href='#10'>How to enter other income generated by the school?</a><br>
<a href='#11'>How to generate and print income report for other income asides school fees?</a><br><br>

<a href='#12'>How to enter other expenses encoured by the school?</a><br>
<a href='#13'>How to generate and print expense report?</a><br><br>

<a href='#14'>How to generate and print profit and loss statement?</a><br>
<!--

<br>
<p><a name='1'>
 <b>How to setup AcadPro?</b></a></p>
<ol>
 <li>Enter the classes
 <li>Enter the Subjects
 <li>Enter Students
 <li>Enter Fees
 <li>Enter Fee Schedule
 <li>Enter Grade Settings
 <li>Enter Non Academic Settings
 <li>Enter School Information
 <li>Enter Session
 <li>Enter Term
 <li>Enter Users
 <li>Types of Income
 <li>Types of Expenses
</ol>


<p><a name='2'>
 <b>How do I generate and print report card for a particular student
 in a class</b></a></p>
<ol>
 <li>Click on 'Student Result' from the menu.
 <li>Choose the term from the drop down for terms.
 <li>Choose the class of the student from the drop down for classes.
 <li>Choose the student from the drop down for students.
 <li>Click 'Generate'.
 <li>A report card is generated for the student
 <li>Click on 'Print' button on the top right corner of the page
     for a printer version of the page
 <li>User your browser to preview the page('File -> Print Preview').
 <li>Adjust your margins to suit your taste.
 <li>Remove top and bottom headers if any.
 <li>Then click 'Print'.
</ol>


<p><b><a name='3'>How do I generate and print school fees receipt for a particular student
 in a class</a></b></p>
<ol>
 <li>Click on 'Student Receipt' from the menu.
 <li>Choose the term from the drop down for terms.
 <li>Choose the class of the student from the drop down for classes.
 <li>Choose the student from the drop down for students.
 <li>Click 'Generate'.
 <li>A receipt is generated for the student
 <li>*Please note that you will get a message 
  if you try to generate/print receipt for a student
  who haven't paid any school fees.
 <li>Click on 'Print' button on the top right corner of the page
     for a printer version of the page
 <li>User your browser to preview the page('File -> Print Preview').
 <li>Adjust your margins to suit your taste.
 <li>Remove top and bottom headers if any.
 <li>Then click 'Print'.
</ol>


<p><b><a name='4'>How to delete a Class?</a></b></p>
<ol>
 <li>Click on 'Class' from the menu
 <li>Choose a class by clicking on one of the radio buttons beside
   the class you want to delete. 
 <li>Click 'Delete'. 
 <li>You are then asked to confirm your delete.
 <li>Click on 'Continue to Delete' to delete the Class.
</ol>

<p><b><a name='5'>How to delete a Subject?</a></b></p>
<ol>
 <li>Click on 'Subject' from the menu
 <li>Choose a subject by clicking on one of the radio buttons beside
   the class you want to delete. 
 <li>Click 'Delete'. 
 <li>You are then asked to confirm your delete.
 <li>Click on 'Continue to Delete' to delete the Subject.
</ol>

<p><b><a name='6'>How to delete a Student?</a></b></p>
<ol>
 <li>Click on 'Student' from the menu
 <li>Choose a student by clicking on one of the radio buttons beside
   the student you want to delete. 
 <li>Click 'Delete'. 
 <li>You are then asked to confirm your delete.
 <li>Click on 'Continue to Delete' to delete the student.
</ol>

<p><b><a name='7'>How to delete a Session?</a></b></p>
<ol>
 <li>Click on 'Session' from the menu
 <li>Choose a student by clicking on one of the radio buttons beside
   the session you want to delete. 
 <li>Click 'Delete'. 
 <li>You are then asked to confirm your delete.
 <li>Click on 'Continue to Delete' to delete the session.
</ol>

<p><b><a name='8'>How to delete a Term?</a></b></p>
<ol>
 <li>Click on 'Term' from the menu
 <li>Choose a student by clicking on one of the radio buttons beside
   the term you want to delete. 
 <li>Click 'Delete'. 
 <li>You are then asked to confirm your delete.
 <li>Click on 'Continue to Delete' to delete the term.
</ol>
-->
</body>
</html>
