<?php
function print_starter() {
echo "<html>
<head>
 <style>
  .a {
    font-size:2em;
	font-weight:800;
  }
  .b {
    font-size:0.7em;
	font-weight:800;
	position:relative;
	top:2px;
	left:20px;
  }
  .c {
    font-size:0.8em;
	position:relative;
	top:3px;
	left:10px;
  }
  .d {
    position:absolute;
	top:32px;
	left:298px;
	border: 1px solid black;
	width:40%;
	height:40%;
  }
  .e {
    font-size:1.5em;
	font-weight:bolder;
	position:relative;
	top:30px;
	left:70px;
  }
  .f {
    font-weight:bold;
  }
    table {
       color:black;
       background-color: white;
       border-width:1px;
       text-align: left;
       padding: 0;
       /*width:50%;*/
       table-layout: float;
       border: #d6e8ff 0.1em solid;
       border-collapse:collapse;
     }
.style4 {font-size: xx-small}
 </style>
</head>
<body>
";
}
?>